/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnit */

#ifndef _Included_jnit
#define _Included_jnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnit
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnit_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
